plugins:
  - jekyll-relative-links
  - jekyll-titles-from-headings
  - jekyll-feed
  - jekyll-seo-tag

title: vojoe

tagline: code and stuff

description: code and stuff

url: johannesvogel.dev

author: Johannes Vogel


defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      permalink: /:basename:output_ext
      layout: "default"
      

