plugins:
  - jekyll-relative-links
  - jekyll-titles-from-headings
  - jekyll-feed
  - jekyll-seo-tag

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

